SET AUTOCOMMIT OFF;

CREATE CLUSTER h_primaire_XXXX (nss INTEGER)
HASHKEYS 3001;
CREATE TABLE XXXX
(
 nss   INTEGER,
 nom   VARCHAR(100) NOT NULL, 
 dist_10   INTEGER,
 dist_100  INTEGER,
 dist_1000  INTEGER,
 dist_10000  INTEGER,
 random  FLOAT
)
CLUSTER h_primaire_XXXX (nss);
ALTER TABLE XXXX
ADD CONSTRAINT XXXX_prim_key_nss
PRIMARY KEY (nss)
USING INDEX;

COMMIT;
exit;
